wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705673223.428633
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.8.13
      5: 0.16.2
      8:
      - 4
      - 5
      13: darwin-arm64
